DOANLAPTRINHWEB/Areas/Admin/Controllers/ProductController.cs
using DOANLAPTRINHWEB.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANLAPTRINHWEB.Areas.Admin.Controllers
{
    [CustomAuthorization(Order = 1)]
    public class ProductController : Controller
    {
        dbWatchDataContext data = new dbWatchDataContext();
        // GET: Admin
        public ActionResult List()
        {
            var L_Watch = from r in data.DONGHOs select r;
            return View(L_Watch);
        }
        public ActionResult Add()
        {
            List<THUONGHIEU> thuonghieu = data.THUONGHIEUs.ToList();
            ViewBag.ThuongHieu = thuonghieu.Select(p => new SelectListItem { Text = p.TenThuongHieu, Value = p.MaThuongHieu.ToString() }).ToList();
            List<LOAIDONGHO> loaidongho = data.LOAIDONGHOs.ToList();
            ViewBag.LoaiDongHo = loaidongho.Select(p => new SelectListItem { Text = p.TenLoaiDongHo, Value = p.MaLoaiDongHo.ToString() }).ToList();
            List<LOAIDAY> loaiday = data.LOAIDAYs.ToList();
            ViewBag.LoaiDay = loaiday.Select(p => new SelectListItem { Text = p.TenLoaiDay, Value = p.MaLoaiDay.ToString() }).ToList();
            List<CHATLIEUMATKINH> chatlieu = data.CHATLIEUMATKINHs.ToList();
            ViewBag.ChatLieu = chatlieu.Select(p => new SelectListItem { Text = p.TenChatLieuMatKinh, Value = p.MaChatLieuMatKinh.ToString() }).ToList();
            List<HINHDANG> hinhdang = data.HINHDANGs.ToList();
            ViewBag.HinhDang = hinhdang.Select(p => new SelectListItem { Text = p.TenHinhDang, Value = p.MaHinhDang.ToString() }).ToList();
            List<KICHTHUOC> kichthuoc = data.KICHTHUOCs.ToList();
            ViewBag.KichThuoc = kichthuoc.Select(p => new SelectListItem { Text = p.TenKichThuoc, Value = p.MaKichThuoc.ToString() }).ToList();
            List<MUCDOCHONGNUOC> mucdochongnuoc = data.MUCDOCHONGNUOCs.ToList();
            ViewBag.MucDoChongNuoc = mucdochongnuoc.Select(p => new SelectListItem { Text = p.TenMucDoChongNuoc, Value = p.MaMucDoChongNuoc.ToString() }).ToList();
            List<GIOITINH> gioitinh = data.GIOITINHs.ToList();
            ViewBag.GioiTinh = gioitinh.Select(p => new SelectListItem { Text = p.TenGioiTinh, Value = p.MaGioiTinh.ToString() }).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Add(FormCollection collection, DONGHO h, HttpPostedFileBase HinhDongHo)
        {
            if (ModelState.IsValid)
            {
                var fileName = Path.GetFileName(HinhDongHo.FileName);
                var path = Path.Combine(Server.MapPath("/Content/images"), fileName);
                HinhDongHo.SaveAs(path);


                var TenDongHo = collection["TenDongHo"];
                var MoTa = collection["MoTa"];
                var GioiTinh = Convert.ToInt32(collection["IDGioiTinh"]);
                var ThoiGianBaoHanh = collection["ThoiGianBaoHanh"];
                var LoaiMay = collection["LoaiMay"];
                var GiaNhap = Convert.ToDouble(collection["GiaNhap"]);
                var GiaBan = Convert.ToDouble(collection["GiaBan"]);
                var IDThuongHieu = Convert.ToInt32(collection["IDThuongHieu"]);
                var IDLoaiDongHo = Convert.ToInt32(collection["IDLoaiDongHo"]);
                var IDLoaiDay = Convert.ToInt32(collection["IDLoaiDay"]);
                var IDChatLieuMatKinh = Convert.ToInt32(collection["IDChatLieuMatKinh"]);
                var IDHinhDangMatSo = Convert.ToInt32(collection["IDHinhDangMatSo"]);
                var IDKichThuocMatSo = Convert.ToInt32(collection["IDKichThuocMatSo"]);
                var IDMucDoChongNuoc = Convert.ToInt32(collection["IDMucDoChongNuoc"]);
                var SoLuongTon = Convert.ToInt32(collection["SoLuongTon"]);

                h.TenDongHo = TenDongHo.ToString();
                h.MoTa = MoTa.ToString();
                h.IDGioiTinh = GioiTinh;
                h.ThoiGianBaoHanh = ThoiGianBaoHanh.ToString();
                h.LoaiMay = LoaiMay.ToString();
                h.GiaNhap = GiaNhap;
                h.GiaBan = GiaBan;
                h.HinhDongHo = "/Content/images/" + fileName;
                h.IDThuongHieu = IDThuongHieu;
                h.IDLoaiDongHo = IDLoaiDongHo;
                h.IDLoaiDay = IDLoaiDay;
                h.IDChatLieuMatKinh = IDChatLieuMatKinh;
                h.IDHinhDangMatSo = IDHinhDangMatSo;
                h.IDKichThuocMatSo = IDKichThuocMatSo;
                h.IDMucDoChongNuoc = IDMucDoChongNuoc;
                h.SLTon = SoLuongTon;
                data.DONGHOs.InsertOnSubmit(h);
                data.SubmitChanges();
                return RedirectToAction("List", "Product");
            }
            else
            {
                return View(h);

            }
        }
        public ActionResult Update(int id)
        {
            var MaDongHo = data.DONGHOs.First(m => m.MaDongHo == id);
            List<THUONGHIEU> thuonghieu = data.THUONGHIEUs.ToList();
            ViewBag.ThuongHieu = thuonghieu.Select(p => new SelectListItem { Text = p.TenThuongHieu, Value = p.MaThuongHieu.ToString() }).ToList();
            List<LOAIDONGHO> loaidongho = data.LOAIDONGHOs.ToList();
            ViewBag.LoaiDongHo = loaidongho.Select(p => new SelectListItem { Text = p.TenLoaiDongHo, Value = p.MaLoaiDongHo.ToString() }).ToList();
            List<LOAIDAY> loaiday = data.LOAIDAYs.ToList();
            ViewBag.LoaiDay = loaiday.Select(p => new SelectListItem { Text = p.TenLoaiDay, Value = p.MaLoaiDay.ToString() }).ToList();
            List<CHATLIEUMATKINH> chatlieu = data.CHATLIEUMATKINHs.ToList();
            ViewBag.ChatLieu = chatlieu.Select(p => new SelectListItem { Text = p.TenChatLieuMatKinh, Value = p.MaChatLieuMatKinh.ToString() }).ToList();
            List<HINHDANG> hinhdang = data.HINHDANGs.ToList();
            ViewBag.HinhDang = hinhdang.Select(p => new SelectListItem { Text = p.TenHinhDang, Value = p.MaHinhDang.ToString() }).ToList();
            List<KICHTHUOC> kichthuoc = data.KICHTHUOCs.ToList();
            ViewBag.KichThuoc = kichthuoc.Select(p => new SelectListItem { Text = p.TenKichThuoc, Value = p.MaKichThuoc.ToString() }).ToList();
            List<MUCDOCHONGNUOC> mucdochongnuoc = data.MUCDOCHONGNUOCs.ToList();
            ViewBag.MucDoChongNuoc = mucdochongnuoc.Select(p => new SelectListItem { Text = p.TenMucDoChongNuoc, Value = p.MaMucDoChongNuoc.ToString() }).ToList();
            List<GIOITINH> gioitinh = data.GIOITINHs.ToList();
            ViewBag.GioiTinh = gioitinh.Select(p => new SelectListItem { Text = p.TenGioiTinh, Value = p.MaGioiTinh.ToString() }).ToList();
            return View(MaDongHo);
        }
        [HttpPost]
        public ActionResult Update(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var MaDongHo = data.DONGHOs.First(m => m.MaDongHo == id);
                var TenDongHo = collection["TenDongHo"];
                var MoTa = collection["MoTa"];
                var GioiTinh = Convert.ToInt32(collection["GioiTinh"]);
                var HinhDongHo = collection["HinhDongHo"];
                var ThoiGianBaoHanh = collection["ThoiGianBaoHanh"];
                var LoaiMay = collection["LoaiMay"];
                var GiaNhap = Convert.ToDouble(collection["GiaNhap"]);
                var GiaBan = Convert.ToDouble(collection["GiaBan"]);
                var IDThuongHieu = Convert.ToInt32(collection["IDThuongHieu"]);
                var IDLoaiDongHo = Convert.ToInt32(collection["IDLoaiDongHo"]);
                var IDLoaiDay = Convert.ToInt32(collection["IDLoaiDay"]);
                var IDChatLieuMatKinh = Convert.ToInt32(collection["IDChatLieuMatKinh"]);
                var IDHinhDangMatSo = Convert.ToInt32(collection["IDHinhDangMatSo"]);
                var IDKichThuocMatSo = Convert.ToInt32(collection["IDKichThuocMatSo"]);
                var IDMucDoChongNuoc = Convert.ToInt32(collection["IDMucDoChongNuoc"]);
                var SoLuongTon = Convert.ToInt32(collection["SoLuongTon"]);

                MaDongHo.TenDongHo = TenDongHo.ToString();
                MaDongHo.MoTa = MoTa.ToString();
                MaDongHo.IDGioiTinh = GioiTinh;
                MaDongHo.ThoiGianBaoHanh = ThoiGianBaoHanh.ToString();
                MaDongHo.LoaiMay = LoaiMay.ToString();
                MaDongHo.GiaNhap = GiaNhap;
                MaDongHo.GiaBan = GiaBan;
                MaDongHo.HinhDongHo = HinhDongHo.ToString();
                MaDongHo.IDThuongHieu = IDThuongHieu;
                MaDongHo.IDLoaiDongHo = IDLoaiDongHo;
                MaDongHo.IDLoaiDay = IDLoaiDay;
                MaDongHo.IDChatLieuMatKinh = IDChatLieuMatKinh;
                MaDongHo.IDHinhDangMatSo = IDHinhDangMatSo;
                MaDongHo.IDKichThuocMatSo = IDKichThuocMatSo;
                MaDongHo.IDMucDoChongNuoc = IDMucDoChongNuoc;
                MaDongHo.SLTon = SoLuongTon;
                UpdateModel(MaDongHo);
                data.SubmitChanges();
            }
            return RedirectToAction("List", "Product");
        }

        public ActionResult Statictical()
        {
            /*Dong ho ban chay nhat thang*/
            var result = from ctdh in data.CTHOADONBANDONGHOs
                         from sp in data.DONGHOs
                         from dh in data.HOADONs
                         where ctdh.IDDongHo == sp.MaDongHo
                            && dh.NgayLap.Value.Month == DateTime.Now.Month
                            && dh.NgayLap.Value.Year == DateTime.Now.Year
                         group ctdh by ctdh.IDDongHo into g
                         select new DongHoBanChay
                         {
                             IDDongHo = g.FirstOrDefault().IDDongHo.Value,

DOANLAPTRINHWEB/Controllers/WatchController.cs
using DOANLAPTRINHWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOANLAPTRINHWEB.Controllers
{
    public class WatchController : Controller
    {
        dbWatchDataContext data = new dbWatchDataContext();
        public ActionResult Index(int gioitinh = 0)
        {
            var I_Watch = from r in data.DONGHOs select r;
            return View(I_Watch);
        }
        public ActionResult Product(string SearchProduct = "", int thuonghieu = 0, int loaiday = 0, int chatlieu = 0, int hinhdang = 0, int kichthuoc = 0, int mucdo = 0, int gioitinh = 0)
        {
            if(SearchProduct != "")
            {
                var search_Watch = data.DONGHOs.Where(p => p.TenDongHo.ToUpper().Contains(SearchProduct.ToUpper())).ToList();
                return View(search_Watch);
            }

            if(thuonghieu != 0)
            {
                var filterThuongHieu = data.DONGHOs.Where(p => p.IDThuongHieu == thuonghieu).ToList();
                return View(filterThuongHieu);
            }
            if (loaiday != 0)
            {
                var filterLoaiDay = data.DONGHOs.Where(p => p.IDLoaiDay == loaiday).ToList();
                return View(filterLoaiDay);
            }
            if (chatlieu != 0)
            {
                var filterChatLieu = data.DONGHOs.Where(p => p.IDChatLieuMatKinh == chatlieu).ToList();
                return View(filterChatLieu);
            }
            if (hinhdang != 0)
            {
                var filterHinhDang = data.DONGHOs.Where(p => p.IDHinhDangMatSo == hinhdang).ToList();
                return View(filterHinhDang);
            }
            if (kichthuoc != 0)
            {
                var filterKichThuoc = data.DONGHOs.Where(p => p.IDKichThuocMatSo == kichthuoc).ToList();
                return View(filterKichThuoc);
            }
            if (mucdo != 0)
            {
                var fillterMucDo = data.DONGHOs.Where(p => p.IDMucDoChongNuoc == mucdo).ToList();
                return View(fillterMucDo);
            }

            if(gioitinh != 0)
            {
                var fillterGioiTinh = data.DONGHOs.Where(p => p.IDGioiTinh == gioitinh).ToList();
                return View(fillterGioiTinh);
            }
            var P_Watch = from r in data.DONGHOs select r;
            return View(P_Watch);
        }
        public ActionResult ProductDetail(int? id)
        {
            var PD_Watch = data.DONGHOs.Where(m => m.MaDongHo == id).First();
            return View(PD_Watch);
        }
        public ActionResult Contact()
        {
            return View();
        }
    }
}

DOANLAPTRINHWEB/Views/Watch/Contact.cshtml

@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('/Content/images/bg-01.jpg');">
    <h2 class="ltext-105 cl0 txt-center">
        Contact
    </h2>
</section>

<!-- Content page -->
<section class="bg0 p-t-104 p-b-116">
    <div class="container">
        <div class="flex-w flex-tr">
            <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
                <form>
                    <h4 class="mtext-105 cl2 txt-center p-b-30">
                        Send Us A Message
                    </h4>

                    <div class="bor8 m-b-20 how-pos4-parent">
                        <input class="stext-111 cl2 plh3 size-116 p-l-62 p-r-30" type="text" name="email" placeholder="Your Email Address">
                        <img class="how-pos4 pointer-none" src="~/Content/images/icons/icon-email.png" alt="ICON">
                    </div>

                    <div class="bor8 m-b-30">
                        <textarea class="stext-111 cl2 plh3 size-120 p-lr-28 p-tb-25" name="msg" placeholder="How Can We Help?"></textarea>
                    </div>

                    <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">
                        Submit
                    </button>
                </form>
            </div>

            <div class="size-210 bor10 flex-w flex-col-m p-lr-93 p-tb-30 p-lr-15-lg w-full-md">
                <div class="flex-w w-full p-b-42">
                    <span class="fs-18 cl5 txt-center size-211">
                        <span class="lnr lnr-map-marker"></span>
                    </span>

                    <div class="size-212 p-t-2">
                        <span class="mtext-110 cl2">
                            Address
                        </span>

                        <p class="stext-115 cl6 size-213 p-t-18">
                            Coza Store Center 8th floor, 379 Hudson St, New York, NY 10018 US
                        </p>
                    </div>
                </div>

                <div class="flex-w w-full p-b-42">
                    <span class="fs-18 cl5 txt-center size-211">
                        <span class="lnr lnr-phone-handset"></span>
                    </span>

                    <div class="size-212 p-t-2">
                        <span class="mtext-110 cl2">
                            Lets Talk
                        </span>

                        <p class="stext-115 cl1 size-213 p-t-18">
                            +1 800 1236879
                        </p>
                    </div>
                </div>

                <div class="flex-w w-full">
                    <span class="fs-18 cl5 txt-center size-211">
                        <span class="lnr lnr-envelope"></span>
                    </span>

                    <div class="size-212 p-t-2">
                        <span class="mtext-110 cl2">
                            Sale Support
                        </span>

                        <p class="stext-115 cl1 size-213 p-t-18">
                            contact@example.com
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Map -->
<div class="map">
    <div class="size-303" id="google_map" data-map-x="40.691446" data-map-y="-73.886787" data-pin="~/Content/images/icons/pin.png" data-scrollwhell="0" data-draggable="1" data-zoom="11"></div>
</div>



DOANLAPTRINHWEB/Views/Watch/Index.cshtml
@model IEnumerable<DOANLAPTRINHWEB.Models.DONGHO>
@using DOANLAPTRINHWEB.Models
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    dbWatchDataContext data = new dbWatchDataContext();
    var gioitinhs = data.GIOITINHs.ToList();
}

<!-- Slider -->
<section class="section-slide">
    <div class="wrap-slick1">
        <div class="slick1">
            <div class="item-slick1" style="background-image: url(/Content/images/banner1.jpg);">
                <div class="container h-full">
                    <div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                            <span class="ltext-101 cl2 respon2" style="color: white">

                            </span>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
                            <h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1" style="color: white">
                                NEW SEASON
                            </h2>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                            <a href="/Watch/Product" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                                Shop Now
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="item-slick1" style="background-image: url(/Content/images/banner2.jpg);">
                <div class="container h-full">
                    <div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                            <span class="ltext-101 cl2 respon2" style="color: white">

                            </span>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
                            <h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1" style="color: white">
                                NEW SEASON
                            </h2>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                            <a href="/Watch/Product" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04" >
                                Shop Now
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="item-slick1" style="background-image: url(/Content/images/banner3.jpg);">
                <div class="container h-full">
                    <div class="flex-col-l-m h-full p-t-100 p-b-30 respon5">
                        <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                            <span class="ltext-101 cl2 respon2" style="color: white">

                            </span>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
                            <h2 class="ltext-201 cl2 p-t-19 p-b-43 respon1" style="color: white">
                                NEW SEASON
                            </h2>
                        </div>

                        <div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                            <a href="/Watch/Product" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                                Shop Now
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
    </div>
</section>

<!-- Banner -->
<div class="sec-banner bg0 p-t-80 p-b-50">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                <div class="block1 wrap-pic-w">
                    <img src="~/Content/images/watchmen.jpg" alt="IMG-BANNER">
                    <a href="@Url.Action("Product", "Watch", new { gioitinh = 1})" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3" name="gioitinh">
                        <div class="block1-txt-child1 flex-col-l" >
                            <span class="block1-name ltext-102 trans-04 p-b-8" style="color: white">
                                Men
                            </span>
                            <span class="block1-info stext-102 trans-04" style="color: white">
                                Spring 2022
                            </span>
                        </div>

                        <div class="block1-txt-child2 p-b-4 trans-05">
                            <div class="block1-link stext-101 cl0 trans-09">
                                Shop Now
                            </div>
                        </div>
                    </a>

                </div>
            </div>
            <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                <div class="block1 wrap-pic-w">
                    <img src="~/Content/images/watchwomen.jpg" alt="IMG-BANNER">
                    <a href="@Url.Action("Product", "Watch", new { gioitinh = 2})" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3" name="gioitinh">
                        <div class="block1-txt-child1 flex-col-l">
                            <span class="block1-name ltext-102 trans-04 p-b-8" style="color: white">
                                Women
                            </span>
                            <span class="block1-info stext-102 trans-04" style="color: white">
                                Spring 2022
                            </span>
                        </div>

                        <div class="block1-txt-child2 p-b-4 trans-05">
                            <div class="block1-link stext-101 cl0 trans-09" style="color: white">
                                Shop Now
                            </div>
                        </div>
                    </a>

                </div>
            </div>
            <div class="col-md-6 col-xl-4 p-b-30 m-lr-auto">
                <div class="block1 wrap-pic-w">
                    <img src="~/Content/images/men_women.jpg" alt="IMG-BANNER">
                    <a href="@Url.Action("Product", "Watch", new { gioitinh = 2})" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3" name="gioitinh">
                        <div class="block1-txt-child1 flex-col-l">
                            <span class="block1-name ltext-102 trans-04 p-b-8" style="color: white">
                                Men & Women
                            </span>
                            <span class="block1-info stext-102 trans-04" style="color: white">
                                Spring 2022
                            </span>
                        </div>

                        <div class="block1-txt-child2 p-b-4 trans-05">
                            <div class="block1-link stext-101 cl0 trans-09">
                                Shop Now
                            </div>
                        </div>
                    </a>

                </div>
            </div>
        </div>
    </div>
</div>


<!-- Product -->
<section class="bg0 p-t-23 p-b-140">
    <div class="container">
        <div class="p-b-10">
            <h3 class="ltext-103 cl5">
                Product Overview
            </h3>
        </div>

        <div class="flex-w flex-sb-m p-b-52">
            <div class="flex-w flex-l-m filter-tope-group m-tb-10">
                <button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">
                    All Products
                </button>
            </div>
        </div>

        <div class="row isotope-grid">
            @foreach (var item in Model)
            {
                <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item watches">
                    <!-- Block2 -->
                    <div class="block2">
                        <div class="block2-pic hov-img0">
                            <img src="@Html.DisplayFor(modelItem => item.HinhDongHo)" alt="IMG-PRODUCT" style=" height: 330px;">

                            <a href="@Url.Action("ProductDetail", "Watch", new {id = item.MaDongHo})" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04">
                                Quick View
                            </a>
                        </div>

                        <div class="block2-txt flex-w flex-t p-t-14">
                            <div class="block2-txt-child1 flex-col-l ">
                                <a href="@Url.Action("ProductDetail", "Watch", new {id = item.MaDongHo})" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                                    @Html.DisplayFor(modelItem => item.TenDongHo)
                                </a>

                                <span class="stext-105 cl3">
                                    @String.Format("{0:0,0}", item.GiaBan) VNĐ
                                </span>
                            </div>

                            <div class="block2-txt-child2 flex-r p-t-3">
                                <a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
                                    <img class="icon-heart1 dis-block trans-04" src="~/Content/images/icons/icon-heart-01.png" alt="ICON">
                                    <img class="icon-heart2 dis-block trans-04 ab-t-l" src="~/Content/images/icons/icon-heart-02.png" alt="ICON">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

        <!-- Load more -->
        <div class="flex-c-m flex-w w-full p-t-45">
            <a href="/Watch/Product" class="flex-c-m stext-101 cl5 size-103 bg2 bor1 hov-btn1 p-lr-15 trans-04">
                Load More
            </a>
        </div>
    </div>
</section>